namespace GitBinder.Desktop.Localization;

/// <summary>
/// 简体中文本地化资源（V1 唯一完整语言）。
/// </summary>
internal static class StringsZhCn
{
    public static readonly IReadOnlyDictionary<string, string> Resources = new Dictionary<string, string>
    {
        ["BINDING_INCOMPLETE"] = "项目或绑定账号已不存在，请重新进入项目页检查绑定。",
        ["TEST_FAILED"] = "连接测试未完成，请检查 Git、项目地址和当前生效账号的认证配置。",
        ["PROJECT_PROTOCOL_SWITCH_UNSUPPORTED"] = "当前账号的认证方式与项目地址协议不匹配，此地址无法安全自动转换。请在“修改地址”中填写平台提供的对应协议地址。",
        ["PROJECT_PROTOCOL_SWITCH_STALE"] = "确认期间项目路径、远程地址或生效账号已变化。未执行协议切换，请重新操作。",
        ["PROJECT_PROTOCOL_SWITCH_FAILED"] = "协议切换未完成，已恢复原地址，请检查仓库权限和账号配置后重试。",
        ["PROJECT_PROTOCOL_SWITCH_ROLLBACK_FAILED"] = "协议切换失败，且未能完整恢复原配置。请在终端/IDE 中核对 origin 地址及仓库认证配置后再操作。",
        ["Projects.BindingReloadFailed"] = "账号绑定已保存，但后续协议检查或页面刷新未完成。请重新进入项目页核对，不必重复添加项目。",
        ["Projects.ProtocolSwitch.ConfirmTitle"] = "确认切换远程协议",
        ["Projects.ProtocolSwitch.ConfirmAction"] = "确认切换",
        ["Projects.ProtocolSwitch.Confirm"] = "当前生效账号“{0}”的认证方式与项目地址协议不匹配。是否将 origin 切换为 {1}？\n\n当前地址：{2}\n切换后：{3}\n\n仅修改本地 origin 地址和该账号的认证配置，不搬移代码、不更换平台，也不修改独立推送地址。取消会保留原地址，不撤销已保存的账号绑定；本次测试或拉取将不再继续。",
        ["TRANSFER_SSH_CONFIG_FAILED"] = "SSH 无法读取隔离配置文件，请检查临时目录权限。\n阶段：{0}\n退出码：{1}",
        ["TRANSFER_HOST_KEY_FAILED"] = "SSH 主机密钥未被信任或已发生变化。请在可信终端核实服务器指纹后再连接，不要直接跳过校验。\n阶段：{0}\n退出码：{1}",
        ["TRANSFER_AUTH_FAILED"] = "远程认证失败：当前生效账号的密钥或 HTTPS 凭据未被服务器接受。\n阶段：{0}\n退出码：{1}",
        ["TRANSFER_DNS_FAILED"] = "无法解析远程主机名，请检查网络、DNS 或仓库地址。\n阶段：{0}\n退出码：{1}",
        ["TRANSFER_CONNECT_FAILED"] = "无法连接远程服务器，请检查网络、防火墙、代理或端口。\n阶段：{0}\n退出码：{1}",
        ["TRANSFER_TIMEOUT"] = "Git/SSH 操作超时，请检查网络连接后重试。\n阶段：{0}\n退出码：{1}",
        ["TRANSFER_CERTIFICATE_FAILED"] = "HTTPS 证书校验失败，请检查服务器证书及 Git 的证书配置。\n阶段：{0}\n退出码：{1}",
        ["TRANSFER_OWNERSHIP_FAILED"] = "Git 拒绝访问此仓库：目录所有者不受信任。请核对目录归属及 safe.directory 配置；软件不会自动信任所有目录。\n阶段：{0}\n退出码：{1}",
        ["TRANSFER_DIVERGED"] = "本地与远程分支已分叉，无法仅快进更新。请在终端/IDE 中处理；软件未自动重置、变基或合并。\n阶段：{0}\n退出码：{1}",
        ["TRANSFER_LOCK_FAILED"] = "Git 无法获取仓库锁。请检查是否有其他 Git 操作正在运行；软件不会自动删除锁文件。\n阶段：{0}\n退出码：{1}",
        ["TRANSFER_PROCESS_MISSING"] = "Git 无法启动 SSH 或凭据助手，请检查程序安装和可执行文件路径。\n阶段：{0}\n退出码：{1}",
        ["TRANSFER_REMOTE_MISSING"] = "远程仓库不存在、地址有误或当前账号没有访问权限。\n阶段：{0}\n退出码：{1}",
        ["TRANSFER_ACCESS_FAILED"] = "访问被拒绝，请检查仓库、密钥或临时目录的权限。\n阶段：{0}\n退出码：{1}",
        ["TRANSFER_LOCAL_IO_FAILED"] = "本地文件操作失败，请检查仓库及临时目录是否可读写、磁盘空间是否充足。\n阶段：{0}\n退出码：{1}",
        ["TRANSFER_COMMAND_FAILED"] = "Git 操作失败，未识别到可安全展示的具体原因；请在终端/IDE 中检查。原始输出未展示，以避免泄露凭据。\n阶段：{0}\n退出码：{1}",
        ["Notice.Title"] = "操作结果",
        ["Notice.Content"] = "提示内容",
        ["Notice.SelectToCopy"] = "选中文字后按 Ctrl+C 复制",
        ["Notice.Close"] = "关闭",
        ["Groups.Title"] = "分组",
        ["Groups.NoResultsHint"] = "可切换分组或调整搜索文字；在“全部项目”中通过项目下拉框设置分组。",
        ["Groups.All"] = "全部项目",
        ["Groups.Ungrouped"] = "未分组",
        ["Groups.New"] = "新建分组",
        ["Groups.Rename"] = "重命名分组",
        ["Groups.EditorHint"] = "用分组整理项目，之后可随时调整项目归属。",
        ["Groups.NamePlaceholder"] = "例如：工作项目",
        ["Groups.Saving"] = "正在保存…",
        ["Groups.Name"] = "分组名称（最多60字）",
        ["Groups.Assign"] = "设置项目分组",
        ["Groups.Delete"] = "删除分组",
        ["Groups.DeleteConfirm"] = "删除分组“{0}”？组内项目将移至“未分组”，不会删除本地代码或解除账号绑定。",
        ["Groups.Saved"] = "分组已保存。",
        ["Groups.Deleted"] = "分组已删除，项目已保留。",
        ["Groups.PullHint"] = "拉取此分组全部项目，不受搜索结果影响。",
        ["Groups.PullConfirm"] = "拉取“{0}”中的全部 {1} 个项目？将忽略当前搜索筛选，依次使用各项目生效账号更新；失败后继续其他项目，不覆盖本地修改。",
        ["Groups.Progress"] = "正在拉取 {0}/{1}：{2}",
        ["Groups.Summary"] = "分组拉取结束：共 {0} 个，成功 {1} 个，失败 {2} 个，未完成 {3} 个。",
        ["Groups.CancelledSummary"] = "分组拉取已取消：共 {0} 个，成功 {1} 个，失败 {2} 个，未完成 {3} 个。",
        ["Groups.Details"] = "查看逐项结果",
        ["GROUP_NAME_INVALID"] = "请输入1～60字的分组名称。",
        ["GROUP_NAME_EXISTS"] = "已有同名分组，请换一个名称。",
        ["GROUP_NOT_FOUND"] = "分组已不存在，请重新加载项目页面。",
        ["GROUP_SAVE_FAILED"] = "分组保存失败，请重试。",
        ["GROUP_RELOAD_FAILED"] = "分组信息刷新失败，请重新进入项目页面核对保存结果。",
        // 通用
        ["Projects.Clone"] = "拉取项目",
        ["Projects.CloneAccount"] = "绑定账号",
        ["Projects.CloneParent"] = "保存到（父目录）",
        ["Projects.CloneFolder"] = "新项目文件夹名称",
        ["Projects.StartClone"] = "开始拉取",
        ["Projects.Pull"] = "拉取",
        ["Projects.CloneHint"] = "填写 HTTPS/SSH 仓库地址，在所选父目录下新建项目文件夹。全局模式下使用全局账号认证，完成后保留所选绑定。不会列出平台的全部仓库。",
        ["Projects.PullHint"] = "使用当前生效账号，快进更新当前分支；不覆盖本地修改或自动合并。",
        ["Projects.TransferRunning"] = "正在使用账号“{0}”传输，请稍候……",
        ["Projects.CancelTransfer"] = "取消传输",
        ["Projects.CloneSuccess"] = "项目已拉取并登记，账号绑定已保存。",
        ["Projects.PullSuccess"] = "当前分支已更新（或已是最新）。",
        ["Projects.TransferReloadFailed"] = "刷新列表失败，请重新进入项目页。",
        ["TRANSFER_BUSY"] = "已有传输任务进行中，请等待或取消。",
        ["TRANSFER_URL_INVALID"] = "请输入不含密码、Token、查询参数的 HTTPS 或 SSH 仓库地址。不支持 HTTP、本地路径或其他协议。",
        ["TRANSFER_ACCOUNT_INVALID"] = "请选择有效且已启用的账号，并检查全局账号设置。",
        ["TRANSFER_HTTPS_REQUIRED"] = "项目地址使用 HTTPS，但当前生效账号未配置 HTTPS 凭据。请完善账号凭据，或在“修改地址”中切换为该账号支持的 SSH 地址。",
        ["TRANSFER_SSH_REQUIRED"] = "项目地址使用 SSH，但当前生效账号未配置可用 SSH 私钥。请检查密钥路径，或在“修改地址”中切换为该账号支持的 HTTPS 地址。",
        ["TRANSFER_HELPER_MISSING"] = "未找到 GitBinder 凭据助手，请使用完整发布版或安装版。",
        ["TRANSFER_GIT_MISSING"] = "未找到 Git，请在设置中配置或重新检测。",
        ["TRANSFER_CANCELLED"] = "传输已取消。已下载文件或已获取的远程记录可能保留，不会自动清理或回滚。",
        ["TRANSFER_FAILED"] = "传输未完成，请检查账号、仓库地址和网络后重试。",
        ["CLONE_PARENT_INVALID"] = "请选择存在的本地父目录，路径必须为绝对路径。",
        ["CLONE_FOLDER_INVALID"] = "请输入有效的单层文件夹名称，不能使用路径、保留名称或特殊字符。",
        ["CLONE_TARGET_EXISTS"] = "目标文件或文件夹已存在，为防止覆盖，请更换项目文件夹名称。",
        ["CLONE_FAILED"] = "克隆未完成：请检查网络、凭据、SSH 主机信任及密钥解锁状态。目标目录可能有残留文件，请检查后换目录重试。",
        ["CLONE_REGISTER_FAILED"] = "代码已克隆，但登记未完成。请用“添加仓库”登记本地目录，不要重复克隆。",
        ["CLONE_BIND_FAILED"] = "代码已克隆并登记，但账号绑定未完成。请在项目卡片中重新选择账号，不要重复克隆。",
        ["PULL_DIRTY"] = "仓库存在本地修改或未跟踪文件，请先在终端/IDE 中处理，再拉取。",
        ["PULL_IN_PROGRESS"] = "仓库正在合并、变基或拣选，请先完成或取消该操作。",
        ["PULL_NO_UPSTREAM"] = "当前分支未跟踪 origin 分支，或处于分离 HEAD 状态。请先在终端/IDE 中设置跟踪分支。",
        ["PULL_FAILED"] = "拉取未完成：可能是网络/认证失败、超时或分支已分叉。请在终端/IDE 中检查；未自动重置、变基或生成合并提交。",
        ["PULL_METADATA_FAILED"] = "代码已更新，但项目信息刷新未完成，请重新进入项目页。",
        ["Common.Save"] = "保存",
        ["Common.Cancel"] = "取消",
        ["Common.Confirm"] = "确认",
        ["Common.Delete"] = "删除",
        ["Common.Edit"] = "编辑",
        ["Common.Add"] = "添加",
        ["Common.Add.New"] = "新增",
        ["Common.Test"] = "测试",
        ["Common.Enable"] = "启用",
        ["Common.Disable"] = "禁用",
        ["Common.Close"] = "关闭",
        ["Common.Yes"] = "是",
        ["Common.No"] = "否",
        ["Common.Alias"] = "别名",
        ["Common.Username"] = "用户名",
        ["Common.Host"] = "主机",
        ["Common.Platform"] = "平台",
        ["Common.Type"] = "类型",
        ["Common.Path"] = "路径",
        ["Common.Name"] = "名称",
        ["Common.Email"] = "邮箱",
        ["Common.Actions"] = "操作",
        ["Common.Status"] = "状态",
        ["Common.Search.Clear"] = "清空搜索",
        ["Common.Search.NoResults"] = "没有匹配的结果",
        ["Common.Search.NoResultsHint"] = "试试其他关键词，或清空搜索查看全部数据。",
        ["Accounts.SearchPlaceholder"] = "搜索账号、姓名、邮箱、平台或主机",
        ["Projects.SearchPlaceholder"] = "搜索项目、路径、远程地址、协议或账号",
        ["Platforms.SearchPlaceholder"] = "搜索平台名称或主机",

        // 导航
        ["Nav.Dashboard"] = "总览",
        ["Nav.Accounts"] = "账号",
        ["Nav.Projects"] = "项目",
        ["Nav.Platforms"] = "平台",
        ["Nav.Settings"] = "设置",
        ["Nav.Logs"] = "日志",

        // App.Tagline 重复 —— 保留原语义
        ["App.Title"] = "GitBind - Git 仓库账号绑定管理",
        ["App.Tagline"] = "本地 Git 账号、仓库及账号绑定关系管理工具",
        ["Ui.Navigation.Section"] = "工作区",
        ["Ui.Navigation.Tagline"] = "仓库身份管理",

        // Dashboard
        ["Dashboard.Accounts"] = "账号总数",
        ["Dashboard.Projects"] = "仓库总数",
        ["Dashboard.Bindings"] = "绑定总数",
        ["Dashboard.DefaultAccount"] = "默认账号",
        ["Dashboard.GlobalMode"] = "全局模式",
        ["Dashboard.BindingProblems"] = "绑定异常",
        ["Dashboard.Off"] = "已关闭",
        ["Dashboard.On"] = "已开启",

        // Global Mode
        ["GlobalMode.Enable"] = "开启全局模式",
        ["GlobalMode.Disable"] = "关闭全局模式",
        ["GlobalMode.ChangeAccount"] = "切换账号",
        ["GlobalMode.EnabledWarning"] = "全局模式已开启",
        ["GlobalMode.Warning"] = "所有经 GitBind 管理的 Git 操作都将强制使用：",
        ["GlobalMode.CurrentAccount"] = "当前账号",
        ["GlobalMode.Account"] = "全局账号",
        ["GlobalMode.Confirm.Title"] = "开启全局模式？",
        ["GlobalMode.Confirm.Message"] = "所有经 GitBind 管理的 Git CLI 操作将强制使用 {0}，原有仓库绑定关系将被临时忽略。",

        // Accounts
        ["Accounts.Title"] = "账号",
        ["Accounts.Add"] = "新增账号",
        ["Accounts.Edit"] = "编辑账号",
        ["Accounts.Delete"] = "删除账号",
        ["Accounts.SetDefault"] = "设为默认",
        ["Accounts.Duplicate"] = "复制账号",
        ["Accounts.Default"] = "默认",
        ["Accounts.CommitIdentity"] = "提交身份",
        ["Accounts.CommitName"] = "提交姓名 (user.name)",
        ["Accounts.CommitEmail"] = "提交邮箱（可选）",
        ["Accounts.Authentication"] = "认证",
        ["Accounts.Ssh"] = "SSH",
        ["Accounts.PrivateKey"] = "私钥",
        ["Accounts.ImportKey"] = "导入私钥",
        ["Accounts.Https"] = "HTTPS",
        ["Accounts.Credential"] = "凭据",
        ["Accounts.CredentialType"] = "凭据类型",
        ["Accounts.Password"] = "密码",
        ["Accounts.AccessToken"] = "访问令牌",
        ["Accounts.PersonalAccessToken"] = "个人访问令牌",
        ["Accounts.Platform.GitHub"] = "GitHub",
        ["Accounts.Platform.Gitee"] = "Gitee",
        ["Accounts.Platform.GitLab"] = "GitLab",
        ["Accounts.Platform.AliyunCodeup"] = "阿里云云效 Codeup",
        ["Accounts.Platform.Tencent"] = "腾讯云代码托管",
        ["Accounts.Platform.Custom"] = "自定义",
        ["Accounts.Delete.Confirm"] = "确定删除账号「{0}」？",
        ["Accounts.Delete.HasBindings"] = "该账号当前绑定 {0} 个项目，请先解除绑定或改绑后再删除。",
        ["Accounts.Delete.DefaultForbidden"] = "默认账号不可删除，请先设置其他默认账号。",
        ["Accounts.Edit.New"] = "新建账号",
        ["Accounts.Edit.Title"] = "编辑账号",
        ["Accounts.Edit.OpenFailed"] = "无法打开账号编辑器，请检查平台数据后重试。",
        ["Accounts.Edit.SaveFailed"] = "账号保存失败，请检查数据目录访问权限、磁盘空间后重试。当前填写内容已保留。",
        ["Accounts.Edit.IdentitySyncFailed"] = "账号已保存，但部分仓库配置未更新。请检查仓库路径和配置权限，修复后重新保存或重启应用，确认生效后再提交。",
        ["Accounts.Block.GitInfo"] = "Git 信息",
        ["Accounts.Block.Https"] = "HTTPS 账密",
        ["Accounts.Block.Https.Hint"] = "用于 HTTPS 方式拉取/推送。留空表示不启用 HTTPS 认证。",
        ["Accounts.Block.Ssh"] = "SSH 私钥",
        ["Accounts.Block.Ssh.Hint"] = "上传私钥后将安全保存到应用目录，用于 SSH 方式拉取/推送。留空表示不启用 SSH 认证。",
        ["Accounts.UploadKey"] = "上传私钥",
        ["Accounts.ClearKey"] = "移除",
        ["Accounts.ClearKey.Confirm"] = "确定移除当前 SSH 私钥吗？保存账号后将不再使用该私钥。",
        ["Accounts.AliasDefaultToName"] = "默认等于提交姓名，可修改",
        ["ACCOUNT_NAME_REQUIRED"] = "提交姓名不能为空。",
        ["ACCOUNT_KEY_NOT_FOUND"] = "私钥文件不存在：{0}。",

        // 平台管理
        ["Platforms.Title"] = "平台",
        ["Platforms.Description"] = "维护 Git 托管平台名称与 Host，账号页平台下拉将读取此列表。",
        ["Platforms.Name"] = "平台名称",
        ["Platforms.NamePlaceholder"] = "如 GitHub、公司 GitLab",
        ["Platforms.HostPlaceholder"] = "如 github.com",
        ["Platforms.RestoreDefaults"] = "恢复默认平台",
        ["Platforms.Enable"] = "启用",
        ["Platforms.Disable"] = "禁用",
        ["Platforms.Status.Enabled"] = "已启用",
        ["Platforms.Status.Disabled"] = "已禁用",
        ["Platforms.Delete.Confirm"] = "确定删除平台「{0}」？关联账号不会被删除，但将不再显示此平台。",
        ["PLATFORM_NAME_REQUIRED"] = "平台名称不能为空。",
        ["PLATFORM_NAME_EXISTS"] = "平台名称已存在：{0}。",
        ["PLATFORM_NOT_FOUND"] = "平台不存在。",
        ["Accounts.AuthType.None"] = "无",
        ["Accounts.AuthType.Ssh"] = "SSH",
        ["Accounts.AuthType.Https"] = "HTTPS",
        ["Accounts.AuthType.Both"] = "SSH + HTTPS",

        // Projects
        ["Projects.Title"] = "项目",
        ["Projects.Add"] = "添加仓库",
        ["Projects.Remove"] = "移除",
        ["Projects.OpenFolder"] = "打开目录",
        ["Projects.OpenTerminal"] = "打开终端",
        ["Projects.EditRemote"] = "修改地址",
        ["Projects.EditPath"] = "修改本地路径",
        ["Projects.LocalPath"] = "本地仓库绝对路径",
        ["Projects.BrowsePath"] = "选择目录",
        ["Projects.SavePath"] = "保存路径",
        ["Projects.PathHint"] = "仅用于重新定位移动后的同一仓库。保留绑定与配置快照，不移动文件，不修改 Git 配置。",
        ["Projects.PathConfirm"] = "请确认新位置是原项目移动后的同一仓库，不是其他仓库或新克隆副本。\n原路径：{0}\n新路径：{1}\n将保留原绑定和配置快照；不会移动文件或修改 Git 配置。是否继续？",
        ["Projects.PathUpdated"] = "本地路径已更新，原绑定与快照已保留。可点击“测试”验证当前生效账号。",
        ["Projects.CachedMetadata"] = "当前展示上次保存的信息。",
        ["Projects.NoOrigin"] = "此仓库尚未配置 origin 远程地址。",
        ["PROJECT_METADATA_READ_FAILED"] = "无法读取或保存本地仓库信息，请检查 Git、仓库路径及访问权限。",
        ["PROJECT_PATH_ABSOLUTE_REQUIRED"] = "请输入完整的本地仓库绝对路径。",
        ["PROJECT_PATH_UPDATE_FAILED"] = "本地路径更新失败，请检查仓库目录和数据目录权限后重试。",
        ["Projects.RemoteUrl"] = "Git 地址",
        ["Projects.RemoteUrlPlaceholder"] = "例如：https://github.com/org/repository.git",
        ["Projects.SwitchProtocol"] = "切换协议",
        ["Projects.SwitchToSsh"] = "切换为 SSH",
        ["Projects.SwitchToHttps"] = "切换为 HTTPS",
        ["Projects.ProtocolSwitch.Unsupported"] = "仅支持标准的 SSH 或 HTTPS Git 地址切换，请手动修改地址。",
        ["Projects.SaveRemote"] = "保存地址",
        ["Projects.Test"] = "测试",
        ["Projects.Name"] = "项目",
        ["Projects.Remote"] = "Remote",
        ["Projects.Remove.Confirm"] = "确定从 GitBind 移除「{0}」？仅移除记录，不会删除本地源码。",
        ["Projects.RepositoryMissing"] = "仓库缺失",

        // Settings
        ["Settings.Title"] = "设置",
        ["Settings.Git"] = "Git",
        ["Settings.RealGit"] = "真实 Git 路径",
        ["Settings.GitVersion"] = "Git 版本",
        ["Settings.Ssh"] = "SSH",
        ["Settings.SshExecutable"] = "SSH 可执行文件",
        ["Settings.Storage"] = "存储",
        ["Settings.Database"] = "数据库",
        ["Settings.DataDirectory"] = "数据目录",
        ["Settings.Security"] = "安全",
        ["Settings.SecretStore"] = "机密存储状态",
        ["Settings.Language"] = "语言",
        ["Settings.Language.Setting"] = "语言设置",

        // 错误码（供 DomainError 本地化）
        ["ACCOUNT_USERNAME_REQUIRED"] = "用户名不能为空。",
        ["ACCOUNT_NOT_FOUND"] = "账号不存在。",
        ["ACCOUNT_DEFAULT_DISABLE_FORBIDDEN"] = "默认账号不可禁用，请先修改默认账号。",
        ["ACCOUNT_DEFAULT_DELETE_FORBIDDEN"] = "默认账号不可删除，请先设置其他默认账号。",
        ["ACCOUNT_HAS_BINDINGS"] = "该账号当前绑定 {0} 个项目，请先解除绑定。",
        ["PROJECT_PATH_REQUIRED"] = "项目路径不能为空。",
        ["PROJECT_REPOSITORY_NOT_FOUND"] = "未找到 Git 仓库：{0}。",
        ["PROJECT_ALREADY_EXISTS"] = "该项目已登记：{0}。",
        ["PROJECT_NOT_FOUND"] = "项目不存在。",
        ["PROJECT_REMOTE_URL_REQUIRED"] = "Git 地址不能为空。",
        ["PROJECT_REMOTE_CREDENTIAL_FORBIDDEN"] = "Git 地址不能包含 HTTPS 用户名、密码或 Token。",
        ["PROJECT_REMOTE_UPDATE_FAILED"] = "无法更新仓库 Git 地址：{0}",
        ["BINDING_ACCOUNT_INVALID"] = "绑定账号无效或已禁用。",
        ["BINDING_APPLY_FAILED"] = "无法将账号应用到仓库本地 Git 配置：{0}",
        ["GLOBALMODE_ACCOUNT_INVALID"] = "全局模式账号无效或已禁用。",
        ["GLOBALMODE_APPLY_FAILED"] = "无法应用全局账号到仓库：{0}",
        ["GLOBALMODE_GLOBAL_CONFIG_FAILED"] = "无法写入 Git 全局配置：{0}",

        // 测试结果
        ["Test.Success"] = "认证成功",
        ["Test.Failed"] = "认证失败",
        ["Test.Duration"] = "测试耗时",
        ["Test.Running"] = "测试中…",

        // ============ View 界面文案 ============
        // 总览页
        ["Dashboard.Title"] = "总览",
        ["Dashboard.Description"] = "本地 Git 账号、仓库及账号绑定关系管理工具",
        ["Dashboard.AccountCount"] = "账号总数",
        ["Dashboard.ProjectCount"] = "仓库总数",
        ["Dashboard.BindingCount"] = "绑定总数",
        ["Dashboard.DefaultAccountLabel"] = "默认账号",
        ["Dashboard.Hero.Kicker"] = "GITBIND 工作台",
        ["Dashboard.Hero.Title"] = "让每个仓库始终使用正确的身份。",
        ["Dashboard.Hero.Body"] = "统一管理账号、仓库与绑定关系，减少提交身份和认证切换带来的干扰。",

        // 账号页
        ["Accounts.Description"] = "管理 Git 账号、提交身份与认证信息",
        ["Accounts.New"] = "新建账号",
        ["Accounts.BasicInfo"] = "基本信息",
        ["Accounts.PlatformLoginUsername"] = "平台登录用户名",
        ["Accounts.AliasPlaceholder"] = "留空则等于用户名",
        ["Accounts.HostPlaceholder"] = "如 github.com",
        ["Accounts.CommitNamePlaceholder"] = "user.name",
        ["Accounts.CommitEmailPlaceholder"] = "留空不携带邮箱",
        ["Accounts.CommitEmailHint"] = "新提交使用实际生效账号的邮箱；留空不继承全局邮箱，不修改已有提交。部分平台可能拒绝空邮箱提交。",
        ["Accounts.SshKeyPlaceholder"] = "私钥文件路径",
        ["Accounts.SshPassphrasePlaceholder"] = "私钥 passphrase（可选）",
        ["Accounts.HttpsUsernameLabel"] = "HTTPS 用户名",
        ["Accounts.HttpsUsernamePlaceholder"] = "HTTPS 认证用户名",
        ["Accounts.HttpsCredentialPlaceholder"] = "Token / 密码（编辑留空不变更）",
        ["Accounts.Edit.Description"] = "管理提交身份与仓库认证信息",

        // 项目页
        ["Projects.Description"] = "集中管理仓库、账号与分组，轻松同步项目代码",
        ["Projects.AddHint"] = "登记本机已存在的 Git 仓库，不会重新下载代码。",
        ["Projects.VisibleCount"] = "显示 {0} / {1} 个项目",
        ["Projects.PickDirectory"] = "选择目录",
        ["Projects.PathPlaceholder"] = "所选仓库路径",
        ["Projects.BindAccount"] = "绑定账号",
        ["Projects.Unbind"] = "解绑",
        ["Projects.BindingRequired"] = "请先为该项目绑定账号。",
        ["Projects.Unbound"] = "未绑定",
        ["Projects.BoundAccountLabel"] = "绑定：{0}",
        ["Projects.EffectiveAccountLabel"] = "生效：{0}",
        ["Projects.Reason.GlobalMode"] = "全局模式覆盖",
        ["Projects.Reason.Binding"] = "绑定生效",
        ["Projects.Reason.Default"] = "默认账号",
        ["Projects.ProtocolLabel"] = "协议：{0}",
        ["Projects.HostLabel"] = "主机：{0}",

        // 设置页
        ["Settings.Description"] = "配置托盘行为、Git、SSH 与数据存储路径",
        ["Settings.General"] = "通用",
        ["Settings.Detect"] = "重新检测",
        ["Settings.LanguageLabel"] = "语言",
        ["Settings.LanguageDesc"] = "切换应用界面语言（立即生效）",
        ["Settings.Tray"] = "系统托盘",
        ["Settings.CloseToTrayDesc"] = "关闭窗口时隐藏到系统托盘，应用继续在后台运行。右键托盘图标可退出应用。",

        // 系统托盘
        ["Tray.Tooltip"] = "GitBind - 仓库身份管理",
        ["Tray.ShowWindow"] = "显示窗口",
        ["Tray.Exit"] = "退出 GitBind",

        // 全局模式横幅
        ["GlobalMode.BannerLabel"] = "GLOBAL MODE",
        ["GlobalMode.CurrentAccountLabel"] = "当前账号：",
        ["GlobalMode.EnableBtn"] = "开启全局模式",
        ["GlobalMode.DisableBtn"] = "关闭全局模式",
        ["Navigation.LoadFailed"] = "页面数据加载失败，请重试。",
    };
}
