namespace GitBinder.Desktop.Localization;

/// <summary>
/// 英文资源占位（V2 完整实现）。当前英文 key 复用中文价值以满足 Key 完整性。
/// </summary>
internal static class StringsEnUs
{
    public static readonly IReadOnlyDictionary<string, string> Resources = new Dictionary<string, string>
    {
        ["Common.Save"] = "Save",
        ["Common.Cancel"] = "Cancel",
        ["Common.Confirm"] = "Confirm",
        ["Common.Delete"] = "Delete",
        ["Common.Edit"] = "Edit",
        ["Common.Add"] = "Add",
        ["Common.Add.New"] = "New",
        ["Common.Test"] = "Test",
        ["Common.Enable"] = "Enable",
        ["Common.Disable"] = "Disable",
        ["Common.Close"] = "Close",
        ["Common.Yes"] = "Yes",
        ["Common.No"] = "No",
        ["Common.Alias"] = "Alias",
        ["Common.Username"] = "Username",
        ["Common.Host"] = "Host",
        ["Common.Platform"] = "Platform",
        ["Common.Type"] = "Type",
        ["Common.Path"] = "Path",
        ["Common.Name"] = "Name",
        ["Common.Email"] = "Email",
        ["Common.Actions"] = "Actions",
        ["Common.Status"] = "Status",
        ["Common.Search.Clear"] = "Clear search",
        ["Common.Search.NoResults"] = "No matching results",
        ["Common.Search.NoResultsHint"] = "Try another keyword or clear the search to see all items.",
        ["Accounts.SearchPlaceholder"] = "Search accounts, names, emails, platforms or hosts",
        ["Projects.SearchPlaceholder"] = "Search projects, paths, remotes, protocols or accounts",
        ["Platforms.SearchPlaceholder"] = "Search platform names or hosts",

        ["Nav.Dashboard"] = "Dashboard",
        ["Nav.Accounts"] = "Accounts",
        ["Nav.Projects"] = "Projects",
        ["Nav.Platforms"] = "Platforms",
        ["Nav.Settings"] = "Settings",
        ["Nav.Logs"] = "Logs",

        ["App.Title"] = "GitBind - Git Repository Account Binding Manager",
        ["App.Tagline"] = "Manage local Git accounts, repositories and their bindings",
        ["Ui.Navigation.Section"] = "WORKSPACE",
        ["Ui.Navigation.Tagline"] = "Repository identity",

        ["Dashboard.Accounts"] = "Accounts",
        ["Dashboard.Projects"] = "Repositories",
        ["Dashboard.Bindings"] = "Bindings",
        ["Dashboard.DefaultAccount"] = "Default Account",
        ["Dashboard.GlobalMode"] = "Global Mode",
        ["Dashboard.BindingProblems"] = "Binding Problems",
        ["Dashboard.Off"] = "Off",
        ["Dashboard.On"] = "On",

        ["GlobalMode.Enable"] = "Enable Global Mode",
        ["GlobalMode.Disable"] = "Disable Global Mode",
        ["GlobalMode.ChangeAccount"] = "Change Account",
        ["GlobalMode.EnabledWarning"] = "GLOBAL MODE ENABLED",
        ["GlobalMode.Warning"] = "All Git operations managed by GitBind will use:",
        ["GlobalMode.CurrentAccount"] = "Current Account",
        ["GlobalMode.Account"] = "Global Account",
        ["GlobalMode.Confirm.Title"] = "Enable Global Mode?",
        ["GlobalMode.Confirm.Message"] = "All Git CLI operations managed by GitBind will use {0}. Existing repository bindings will be temporarily ignored.",

        ["Accounts.Title"] = "Accounts",
        ["Accounts.Add"] = "Add Account",
        ["Accounts.Edit"] = "Edit Account",
        ["Accounts.Delete"] = "Delete Account",
        ["Accounts.SetDefault"] = "Set Default",
        ["Accounts.Duplicate"] = "Duplicate",
        ["Accounts.Default"] = "Default",
        ["Accounts.CommitIdentity"] = "Commit Identity",
        ["Accounts.CommitName"] = "Commit Name (user.name)",
        ["Accounts.CommitEmail"] = "Commit Email (user.email)",
        ["Accounts.Authentication"] = "Authentication",
        ["Accounts.Ssh"] = "SSH",
        ["Accounts.PrivateKey"] = "Private Key",
        ["Accounts.ImportKey"] = "Import Key",
        ["Accounts.Https"] = "HTTPS",
        ["Accounts.Credential"] = "Credential",
        ["Accounts.CredentialType"] = "Credential Type",
        ["Accounts.Password"] = "Password",
        ["Accounts.AccessToken"] = "Access Token",
        ["Accounts.PersonalAccessToken"] = "Personal Access Token",
        ["Accounts.Platform.GitHub"] = "GitHub",
        ["Accounts.Platform.Gitee"] = "Gitee",
        ["Accounts.Platform.GitLab"] = "GitLab",
        ["Accounts.Platform.AliyunCodeup"] = "Aliyun Codeup",
        ["Accounts.Platform.Tencent"] = "Tencent",
        ["Accounts.Platform.Custom"] = "Custom",
        ["Accounts.Delete.Confirm"] = "Delete account \"{0}\"?",
        ["Accounts.Delete.HasBindings"] = "This account is bound to {0} projects. Unbind or rebind them first.",
        ["Accounts.Delete.DefaultForbidden"] = "Default account cannot be deleted. Set another default account first.",
        ["Accounts.Edit.New"] = "New Account",
        ["Accounts.Edit.Title"] = "Edit Account",
        ["Accounts.Edit.OpenFailed"] = "Unable to open the account editor. Check the platform data and try again.",
        ["Accounts.Block.GitInfo"] = "Git Info",
        ["Accounts.Block.Https"] = "HTTPS Credentials",
        ["Accounts.Block.Https.Hint"] = "Used for HTTPS pull/push. Leave empty to disable HTTPS auth.",
        ["Accounts.Block.Ssh"] = "SSH Private Key",
        ["Accounts.Block.Ssh.Hint"] = "Uploaded key is stored securely in the app directory, used for SSH pull/push. Leave empty to disable SSH auth.",
        ["Accounts.UploadKey"] = "Upload Key",
        ["Accounts.ClearKey"] = "Remove",
        ["Accounts.ClearKey.Confirm"] = "Remove the current SSH private key? It will no longer be used after the account is saved.",
        ["Accounts.AliasDefaultToName"] = "Defaults to commit name, editable",
        ["ACCOUNT_NAME_REQUIRED"] = "Commit name is required.",
        ["ACCOUNT_KEY_NOT_FOUND"] = "Private key file not found: {0}.",

        ["Platforms.Title"] = "Platforms",
        ["Platforms.Description"] = "Manage Git hosting platform names and hosts. The account platform dropdown reads this list.",
        ["Platforms.Name"] = "Platform Name",
        ["Platforms.NamePlaceholder"] = "e.g. GitHub, Company GitLab",
        ["Platforms.HostPlaceholder"] = "e.g. github.com",
        ["Platforms.RestoreDefaults"] = "Restore Default Platforms",
        ["Platforms.Enable"] = "Enable",
        ["Platforms.Disable"] = "Disable",
        ["Platforms.Status.Enabled"] = "Enabled",
        ["Platforms.Status.Disabled"] = "Disabled",
        ["Platforms.Delete.Confirm"] = "Delete platform \"{0}\"? Associated accounts are retained, but this platform will no longer be listed.",
        ["PLATFORM_NAME_REQUIRED"] = "Platform name is required.",
        ["PLATFORM_NAME_EXISTS"] = "Platform name already exists: {0}.",
        ["PLATFORM_NOT_FOUND"] = "Platform not found.",
        ["Accounts.AuthType.None"] = "None",
        ["Accounts.AuthType.Ssh"] = "SSH",
        ["Accounts.AuthType.Https"] = "HTTPS",
        ["Accounts.AuthType.Both"] = "SSH + HTTPS",

        ["Projects.Title"] = "Projects",
        ["Projects.Add"] = "Add Repository",
        ["Projects.Remove"] = "Remove",
        ["Projects.OpenFolder"] = "Open Folder",
        ["Projects.OpenTerminal"] = "Open Terminal",
        ["Projects.EditRemote"] = "Edit URL",
        ["Projects.RemoteUrl"] = "Git URL",
        ["Projects.RemoteUrlPlaceholder"] = "Example: https://github.com/org/repository.git",
        ["Projects.SwitchProtocol"] = "Switch Protocol",
        ["Projects.SwitchToSsh"] = "Switch to SSH",
        ["Projects.SwitchToHttps"] = "Switch to HTTPS",
        ["Projects.ProtocolSwitch.Unsupported"] = "Only standard SSH and HTTPS Git URLs can be switched. Edit the URL manually.",
        ["Projects.SaveRemote"] = "Save URL",
        ["Projects.Test"] = "Test",
        ["Projects.Name"] = "Project",
        ["Projects.Remote"] = "Remote",
        ["Projects.Remove.Confirm"] = "Remove \"{0}\" from GitBind? Only the record is removed; local source is not deleted.",
        ["Projects.RepositoryMissing"] = "Repository Missing",

        ["Settings.Title"] = "Settings",
        ["Settings.Git"] = "Git",
        ["Settings.RealGit"] = "Real Git Path",
        ["Settings.GitVersion"] = "Git Version",
        ["Settings.Ssh"] = "SSH",
        ["Settings.SshExecutable"] = "SSH Executable",
        ["Settings.Storage"] = "Storage",
        ["Settings.Database"] = "Database",
        ["Settings.DataDirectory"] = "Data Directory",
        ["Settings.Security"] = "Security",
        ["Settings.SecretStore"] = "Secret Store Status",
        ["Settings.Language"] = "Language",
        ["Settings.Language.Setting"] = "Language Setting",

        ["ACCOUNT_USERNAME_REQUIRED"] = "Username is required.",
        ["ACCOUNT_NOT_FOUND"] = "Account not found.",
        ["ACCOUNT_DEFAULT_DISABLE_FORBIDDEN"] = "Default account cannot be disabled.",
        ["ACCOUNT_DEFAULT_DELETE_FORBIDDEN"] = "Default account cannot be deleted.",
        ["ACCOUNT_HAS_BINDINGS"] = "This account is bound to {0} projects.",
        ["PROJECT_PATH_REQUIRED"] = "Project path is required.",
        ["PROJECT_REPOSITORY_NOT_FOUND"] = "Git repository not found: {0}.",
        ["PROJECT_ALREADY_EXISTS"] = "Project already exists: {0}.",
        ["PROJECT_NOT_FOUND"] = "Project not found.",
        ["PROJECT_REMOTE_URL_REQUIRED"] = "Git URL is required.",
        ["PROJECT_REMOTE_CREDENTIAL_FORBIDDEN"] = "Git URL must not contain an HTTPS username, password, or token.",
        ["PROJECT_REMOTE_UPDATE_FAILED"] = "Unable to update the repository Git URL: {0}",
        ["BINDING_ACCOUNT_INVALID"] = "Binding account is invalid or disabled.",
        ["BINDING_APPLY_FAILED"] = "Unable to apply the account to the repository local Git configuration: {0}",
        ["GLOBALMODE_ACCOUNT_INVALID"] = "Global mode account is invalid or disabled.",
        ["GLOBALMODE_APPLY_FAILED"] = "Unable to apply the global account to repository: {0}",
        ["GLOBALMODE_GLOBAL_CONFIG_FAILED"] = "Unable to update Git global configuration: {0}",

        ["Test.Success"] = "Authentication succeeded",
        ["Test.Failed"] = "Authentication failed",
        ["Test.Duration"] = "Duration",
        ["Test.Running"] = "Testing…",

        // ============ View Texts ============
        ["Dashboard.Title"] = "Dashboard",
        ["Dashboard.Description"] = "Manage local Git accounts, repositories and their bindings",
        ["Dashboard.AccountCount"] = "Accounts",
        ["Dashboard.ProjectCount"] = "Repositories",
        ["Dashboard.BindingCount"] = "Bindings",
        ["Dashboard.DefaultAccountLabel"] = "Default Account",
        ["Dashboard.Hero.Kicker"] = "GITBIND WORKSPACE",
        ["Dashboard.Hero.Title"] = "Keep every repository on the right identity.",
        ["Dashboard.Hero.Body"] = "Manage accounts, repositories and bindings in one place with fewer identity and authentication switches.",

        ["Accounts.Description"] = "Manage Git accounts, commit identity and authentication",
        ["Accounts.New"] = "New Account",
        ["Accounts.BasicInfo"] = "Basic Info",
        ["Accounts.PlatformLoginUsername"] = "Platform login username",
        ["Accounts.AliasPlaceholder"] = "Defaults to username when empty",
        ["Accounts.HostPlaceholder"] = "e.g. github.com",
        ["Accounts.CommitNamePlaceholder"] = "user.name",
        ["Accounts.CommitEmailPlaceholder"] = "user.email",
        ["Accounts.SshKeyPlaceholder"] = "Private key file path",
        ["Accounts.SshPassphrasePlaceholder"] = "Private key passphrase (optional)",
        ["Accounts.HttpsUsernameLabel"] = "HTTPS Username",
        ["Accounts.HttpsUsernamePlaceholder"] = "HTTPS auth username",
        ["Accounts.HttpsCredentialPlaceholder"] = "Token / password (leave empty to keep unchanged)",
        ["Accounts.Edit.Description"] = "Manage commit identity and repository authentication",

        ["Projects.Description"] = "Register local Git repositories and manage bound accounts",
        ["Projects.PickDirectory"] = "Pick Directory",
        ["Projects.PathPlaceholder"] = "Selected repository path",
        ["Projects.BindAccount"] = "Bound Account",
        ["Projects.Unbind"] = "Unbind",
        ["Projects.BindingRequired"] = "Bind an account to this repository first.",
        ["Projects.Unbound"] = "Unbound",
        ["Projects.BoundAccountLabel"] = "Bound: {0}",
        ["Projects.EffectiveAccountLabel"] = "Effective: {0}",
        ["Projects.Reason.GlobalMode"] = "Global Override",
        ["Projects.Reason.Binding"] = "Binding",
        ["Projects.Reason.Default"] = "Default Account",
        ["Projects.ProtocolLabel"] = "Protocol: {0}",
        ["Projects.HostLabel"] = "Host: {0}",

        ["Settings.Description"] = "Configure tray behavior, Git, SSH and data storage paths",
        ["Settings.Detect"] = "Re-detect",
        ["Settings.LanguageLabel"] = "Language",
        ["Settings.LanguageDesc"] = "Switch UI language (takes effect immediately)",
        ["Settings.Tray"] = "System Tray",
        ["Settings.CloseToTrayDesc"] = "Hide to the system tray when the window closes and keep GitBind running in the background. Right-click the tray icon to exit.",

        ["Tray.Tooltip"] = "GitBind - Repository Identity Manager",
        ["Tray.ShowWindow"] = "Show Window",
        ["Tray.Exit"] = "Exit GitBind",

        ["GlobalMode.BannerLabel"] = "GLOBAL MODE",
        ["GlobalMode.CurrentAccountLabel"] = "Current account:",
        ["GlobalMode.EnableBtn"] = "Enable Global Mode",
        ["GlobalMode.DisableBtn"] = "Disable Global Mode",
        ["Navigation.LoadFailed"] = "Unable to load page data. Please try again.",
    };
}
