namespace GitBinder.Desktop.Localization;

/// <summary>
/// 简体中文本地化资源（V1 唯一完整语言）。
/// </summary>
internal static class StringsZhCn
{
    public static readonly IReadOnlyDictionary<string, string> Resources = new Dictionary<string, string>
    {
        // 通用
        ["Common.Save"] = "保存",
        ["Common.Cancel"] = "取消",
        ["Common.Confirm"] = "确认",
        ["Common.Delete"] = "删除",
        ["Common.Edit"] = "编辑",
        ["Common.Add"] = "添加",
        ["Common.Add.New"] = "新增",
        ["Common.Test"] = "测试",
        ["Common.Enable"] = "启用",
        ["Common.Disable"] = "禁用",
        ["Common.Close"] = "关闭",
        ["Common.Yes"] = "是",
        ["Common.No"] = "否",
        ["Common.Alias"] = "别名",
        ["Common.Username"] = "用户名",
        ["Common.Host"] = "主机",
        ["Common.Platform"] = "平台",
        ["Common.Type"] = "类型",
        ["Common.Path"] = "路径",
        ["Common.Name"] = "名称",
        ["Common.Email"] = "邮箱",
        ["Common.Actions"] = "操作",
        ["Common.Status"] = "状态",

        // 导航
        ["Nav.Dashboard"] = "总览",
        ["Nav.Accounts"] = "账号",
        ["Nav.Projects"] = "项目",
        ["Nav.Platforms"] = "平台",
        ["Nav.Settings"] = "设置",
        ["Nav.Logs"] = "日志",

        // App.Tagline 重复 —— 保留原语义
        ["App.Title"] = "GitBind - Git 仓库账号绑定管理",
        ["App.Tagline"] = "本地 Git 账号、仓库及账号绑定关系管理工具",
        ["Ui.Navigation.Section"] = "工作区",

        // Dashboard
        ["Dashboard.Accounts"] = "账号总数",
        ["Dashboard.Projects"] = "仓库总数",
        ["Dashboard.Bindings"] = "绑定总数",
        ["Dashboard.DefaultAccount"] = "默认账号",
        ["Dashboard.GlobalMode"] = "全局模式",
        ["Dashboard.BindingProblems"] = "绑定异常",
        ["Dashboard.Off"] = "已关闭",
        ["Dashboard.On"] = "已开启",

        // Global Mode
        ["GlobalMode.Enable"] = "开启全局模式",
        ["GlobalMode.Disable"] = "关闭全局模式",
        ["GlobalMode.ChangeAccount"] = "切换账号",
        ["GlobalMode.EnabledWarning"] = "全局模式已开启",
        ["GlobalMode.Warning"] = "所有经 GitBind 管理的 Git 操作都将强制使用：",
        ["GlobalMode.CurrentAccount"] = "当前账号",
        ["GlobalMode.Account"] = "全局账号",
        ["GlobalMode.Confirm.Title"] = "开启全局模式？",
        ["GlobalMode.Confirm.Message"] = "所有经 GitBind 管理的 Git CLI 操作将强制使用 {0}，原有仓库绑定关系将被临时忽略。",

        // Accounts
        ["Accounts.Title"] = "账号",
        ["Accounts.Add"] = "新增账号",
        ["Accounts.Edit"] = "编辑账号",
        ["Accounts.Delete"] = "删除账号",
        ["Accounts.SetDefault"] = "设为默认",
        ["Accounts.Duplicate"] = "复制账号",
        ["Accounts.Default"] = "默认",
        ["Accounts.CommitIdentity"] = "提交身份",
        ["Accounts.CommitName"] = "提交姓名 (user.name)",
        ["Accounts.CommitEmail"] = "提交邮箱 (user.email)",
        ["Accounts.Authentication"] = "认证",
        ["Accounts.Ssh"] = "SSH",
        ["Accounts.PrivateKey"] = "私钥",
        ["Accounts.ImportKey"] = "导入私钥",
        ["Accounts.Https"] = "HTTPS",
        ["Accounts.Credential"] = "凭据",
        ["Accounts.CredentialType"] = "凭据类型",
        ["Accounts.Password"] = "密码",
        ["Accounts.AccessToken"] = "访问令牌",
        ["Accounts.PersonalAccessToken"] = "个人访问令牌",
        ["Accounts.Platform.GitHub"] = "GitHub",
        ["Accounts.Platform.Gitee"] = "Gitee",
        ["Accounts.Platform.GitLab"] = "GitLab",
        ["Accounts.Platform.AliyunCodeup"] = "阿里云云效 Codeup",
        ["Accounts.Platform.Tencent"] = "腾讯云代码托管",
        ["Accounts.Platform.Custom"] = "自定义",
        ["Accounts.Delete.Confirm"] = "确定删除账号「{0}」？",
        ["Accounts.Delete.HasBindings"] = "该账号当前绑定 {0} 个项目，请先解除绑定或改绑后再删除。",
        ["Accounts.Delete.DefaultForbidden"] = "默认账号不可删除，请先设置其他默认账号。",
        ["Accounts.Edit.New"] = "新建账号",
        ["Accounts.Edit.Title"] = "编辑账号",
        ["Accounts.Edit.OpenFailed"] = "无法打开账号编辑器，请检查平台数据后重试。",
        ["Accounts.Block.GitInfo"] = "Git 信息",
        ["Accounts.Block.Https"] = "HTTPS 账密",
        ["Accounts.Block.Https.Hint"] = "用于 HTTPS 方式拉取/推送。留空表示不启用 HTTPS 认证。",
        ["Accounts.Block.Ssh"] = "SSH 私钥",
        ["Accounts.Block.Ssh.Hint"] = "上传私钥后将安全保存到应用目录，用于 SSH 方式拉取/推送。留空表示不启用 SSH 认证。",
        ["Accounts.UploadKey"] = "上传私钥",
        ["Accounts.ClearKey"] = "移除",
        ["Accounts.ClearKey.Confirm"] = "确定移除当前 SSH 私钥吗？保存账号后将不再使用该私钥。",
        ["Accounts.AliasDefaultToName"] = "默认等于提交姓名，可修改",
        ["ACCOUNT_NAME_REQUIRED"] = "提交姓名不能为空。",
        ["ACCOUNT_KEY_NOT_FOUND"] = "私钥文件不存在：{0}。",

        // 平台管理
        ["Platforms.Title"] = "平台",
        ["Platforms.Description"] = "维护 Git 托管平台名称与 Host，账号页平台下拉将读取此列表。",
        ["Platforms.Name"] = "平台名称",
        ["Platforms.NamePlaceholder"] = "如 GitHub、公司 GitLab",
        ["Platforms.HostPlaceholder"] = "如 github.com",
        ["Platforms.RestoreDefaults"] = "恢复默认平台",
        ["Platforms.Enable"] = "启用",
        ["Platforms.Disable"] = "禁用",
        ["Platforms.Status.Enabled"] = "已启用",
        ["Platforms.Status.Disabled"] = "已禁用",
        ["Platforms.Delete.Confirm"] = "确定删除平台「{0}」？关联账号不会被删除，但将不再显示此平台。",
        ["PLATFORM_NAME_REQUIRED"] = "平台名称不能为空。",
        ["PLATFORM_NAME_EXISTS"] = "平台名称已存在：{0}。",
        ["PLATFORM_NOT_FOUND"] = "平台不存在。",
        ["Accounts.AuthType.None"] = "无",
        ["Accounts.AuthType.Ssh"] = "SSH",
        ["Accounts.AuthType.Https"] = "HTTPS",
        ["Accounts.AuthType.Both"] = "SSH + HTTPS",

        // Projects
        ["Projects.Title"] = "项目",
        ["Projects.Add"] = "添加仓库",
        ["Projects.Remove"] = "移除",
        ["Projects.OpenFolder"] = "打开目录",
        ["Projects.OpenTerminal"] = "打开终端",
        ["Projects.EditRemote"] = "修改地址",
        ["Projects.RemoteUrl"] = "Git 地址",
        ["Projects.RemoteUrlPlaceholder"] = "例如：https://github.com/org/repository.git",
        ["Projects.SwitchProtocol"] = "切换协议",
        ["Projects.SwitchToSsh"] = "切换为 SSH",
        ["Projects.SwitchToHttps"] = "切换为 HTTPS",
        ["Projects.ProtocolSwitch.Unsupported"] = "仅支持标准的 SSH 或 HTTPS Git 地址切换，请手动修改地址。",
        ["Projects.SaveRemote"] = "保存地址",
        ["Projects.Test"] = "测试",
        ["Projects.Name"] = "项目",
        ["Projects.Remote"] = "Remote",
        ["Projects.Remove.Confirm"] = "确定从 GitBind 移除「{0}」？仅移除记录，不会删除本地源码。",
        ["Projects.RepositoryMissing"] = "仓库缺失",

        // Settings
        ["Settings.Title"] = "设置",
        ["Settings.Git"] = "Git",
        ["Settings.RealGit"] = "真实 Git 路径",
        ["Settings.GitVersion"] = "Git 版本",
        ["Settings.Ssh"] = "SSH",
        ["Settings.SshExecutable"] = "SSH 可执行文件",
        ["Settings.Storage"] = "存储",
        ["Settings.Database"] = "数据库",
        ["Settings.DataDirectory"] = "数据目录",
        ["Settings.Security"] = "安全",
        ["Settings.SecretStore"] = "机密存储状态",
        ["Settings.Language"] = "语言",
        ["Settings.Language.Setting"] = "语言设置",

        // 错误码（供 DomainError 本地化）
        ["ACCOUNT_USERNAME_REQUIRED"] = "用户名不能为空。",
        ["ACCOUNT_NOT_FOUND"] = "账号不存在。",
        ["ACCOUNT_DEFAULT_DISABLE_FORBIDDEN"] = "默认账号不可禁用，请先修改默认账号。",
        ["ACCOUNT_DEFAULT_DELETE_FORBIDDEN"] = "默认账号不可删除，请先设置其他默认账号。",
        ["ACCOUNT_HAS_BINDINGS"] = "该账号当前绑定 {0} 个项目，请先解除绑定。",
        ["PROJECT_PATH_REQUIRED"] = "项目路径不能为空。",
        ["PROJECT_REPOSITORY_NOT_FOUND"] = "未找到 Git 仓库：{0}。",
        ["PROJECT_ALREADY_EXISTS"] = "该项目已登记：{0}。",
        ["PROJECT_NOT_FOUND"] = "项目不存在。",
        ["PROJECT_REMOTE_URL_REQUIRED"] = "Git 地址不能为空。",
        ["PROJECT_REMOTE_CREDENTIAL_FORBIDDEN"] = "Git 地址不能包含 HTTPS 用户名、密码或 Token。",
        ["PROJECT_REMOTE_UPDATE_FAILED"] = "无法更新仓库 Git 地址：{0}",
        ["BINDING_ACCOUNT_INVALID"] = "绑定账号无效或已禁用。",
        ["BINDING_APPLY_FAILED"] = "无法将账号应用到仓库本地 Git 配置：{0}",
        ["GLOBALMODE_ACCOUNT_INVALID"] = "全局模式账号无效或已禁用。",
        ["GLOBALMODE_APPLY_FAILED"] = "无法应用全局账号到仓库：{0}",
        ["GLOBALMODE_GLOBAL_CONFIG_FAILED"] = "无法写入 Git 全局配置：{0}",

        // 测试结果
        ["Test.Success"] = "认证成功",
        ["Test.Failed"] = "认证失败",
        ["Test.Duration"] = "测试耗时",
        ["Test.Running"] = "测试中…",

        // ============ View 界面文案 ============
        // 总览页
        ["Dashboard.Title"] = "总览",
        ["Dashboard.Description"] = "本地 Git 账号、仓库及账号绑定关系管理工具",
        ["Dashboard.AccountCount"] = "账号总数",
        ["Dashboard.ProjectCount"] = "仓库总数",
        ["Dashboard.BindingCount"] = "绑定总数",
        ["Dashboard.DefaultAccountLabel"] = "默认账号",
        ["Dashboard.Hero.Kicker"] = "GITBIND 工作台",
        ["Dashboard.Hero.Title"] = "让每个仓库始终使用正确的身份。",
        ["Dashboard.Hero.Body"] = "统一管理账号、仓库与绑定关系，减少提交身份和认证切换带来的干扰。",

        // 账号页
        ["Accounts.Description"] = "管理 Git 账号、提交身份与认证信息",
        ["Accounts.New"] = "新建账号",
        ["Accounts.BasicInfo"] = "基本信息",
        ["Accounts.PlatformLoginUsername"] = "平台登录用户名",
        ["Accounts.AliasPlaceholder"] = "留空则等于用户名",
        ["Accounts.HostPlaceholder"] = "如 github.com",
        ["Accounts.CommitNamePlaceholder"] = "user.name",
        ["Accounts.CommitEmailPlaceholder"] = "user.email",
        ["Accounts.SshKeyPlaceholder"] = "私钥文件路径",
        ["Accounts.SshPassphrasePlaceholder"] = "私钥 passphrase（可选）",
        ["Accounts.HttpsUsernameLabel"] = "HTTPS 用户名",
        ["Accounts.HttpsUsernamePlaceholder"] = "HTTPS 认证用户名",
        ["Accounts.HttpsCredentialPlaceholder"] = "Token / 密码（编辑留空不变更）",
        ["Accounts.Edit.Description"] = "管理提交身份与仓库认证信息",

        // 项目页
        ["Projects.Description"] = "登记本机已有的 Git 仓库并管理绑定账号",
        ["Projects.PickDirectory"] = "选择目录",
        ["Projects.PathPlaceholder"] = "所选仓库路径",
        ["Projects.BindAccount"] = "绑定账号",
        ["Projects.Unbind"] = "解绑",
        ["Projects.BindingRequired"] = "请先为该项目绑定账号。",
        ["Projects.Unbound"] = "未绑定",
        ["Projects.BoundAccountLabel"] = "绑定：{0}",
        ["Projects.EffectiveAccountLabel"] = "生效：{0}",
        ["Projects.Reason.GlobalMode"] = "全局模式覆盖",
        ["Projects.Reason.Binding"] = "绑定生效",
        ["Projects.Reason.Default"] = "默认账号",
        ["Projects.ProtocolLabel"] = "协议：{0}",
        ["Projects.HostLabel"] = "主机：{0}",

        // 设置页
        ["Settings.Description"] = "配置托盘行为、Git、SSH 与数据存储路径",
        ["Settings.Detect"] = "重新检测",
        ["Settings.LanguageLabel"] = "语言",
        ["Settings.LanguageDesc"] = "切换应用界面语言（立即生效）",
        ["Settings.Tray"] = "系统托盘",
        ["Settings.CloseToTrayDesc"] = "关闭窗口时隐藏到系统托盘，应用继续在后台运行。右键托盘图标可退出应用。",

        // 系统托盘
        ["Tray.Tooltip"] = "GitBind - 仓库身份管理",
        ["Tray.ShowWindow"] = "显示窗口",
        ["Tray.Exit"] = "退出 GitBind",

        // 全局模式横幅
        ["GlobalMode.BannerLabel"] = "GLOBAL MODE",
        ["GlobalMode.CurrentAccountLabel"] = "当前账号：",
        ["GlobalMode.EnableBtn"] = "开启全局模式",
        ["GlobalMode.DisableBtn"] = "关闭全局模式",
        ["Navigation.LoadFailed"] = "页面数据加载失败，请重试。",
    };
}
